#!/usr/bin/env -S ansible-playbook --ask-pass

---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: ensure git,neovim,tmux installed
    package:
      name: "{{ item }}"
      state: installed
    become: yes
    loop:
      - zsh
      - neovim
      - git
      - tmux
      - rcm
      - lsd

  - name: init oh-my-zsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    args:
      creates: ~/.oh-my-zsh/

  - name: init powerlevel10k
    git:
      repo: "https://github.com/romkatv/powerlevel10k.git"
      dest: ~/.oh-my-zsh/themes/powerlevel10k

  - name: install dein plugin manager
    shell: |
      curl -fsSL https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh -o /tmp/dein-installer.sh
      /tmp/dein-installer.sh ~/.local/share/dein 
      rm /tmp/dein-installer.sh
    args:
      creates: ~/.local/share/dein

  - name: call rcup
    shell: rcup
